name: RuneKT
version: 'v0.1'
main: net.runemc.plugin.Main
api-version: '1.21'
libraries:
  - org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.20.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.20.0

commands:
  script:
    aliases:
      - scripts
      - scr
